phrases = {
    "greeting": "Привет! Я бот, который поможет Вам искать новости университетов",
    "to_begin": "Начать",
    "one_time_getting_news": "Разово получить новости",
    "subscribe": "Подписаться",
    "unsubscribe": "Отписаться",
    "change_time": "Сменить время",
    "message_for_first_interaction": "Выберите следующее действие под полем ввода",
    "message_to_re_interact": "Если нужно, выберите следующие действия под полем ввода",
    "select_university": "Выберите университет:",
    "select_time_period": "Выберите период вермени:",
    "for_last_day": "За последний день",
    "for_last_week": "За последнюю неделю",
    "for_last_month": "За последний месяц",
    "over_past_six_months": "За последние полгода",
    "university_achievements": "Достижения университета",
    "students_achievements": "Достижения студентов",
    "education": "Образование",
    "cooperation": "Сотрудничество и партнёрство",
    "university_life": "Жизнь университета",
    "science": "Наука",
    "official_documents": "Официальные документы",
    "miscellanea": "Разное",
    "any_topic": "Любая тема",
    "select_topic": "Выберите тему, если нужно:",
    "yes": "Да",
    "no": "Нет",
    "question_of_continuing_to_show_news": "Показать следующие новости?",
    "add_topic": "Добавить тему",
    "any_topic_success": "Теперь к Вам проиходят новости всех тем!",
    "add_topic_success": "Тема успешно добавлена!",
    "add_topic_failure": "У вас уже выбрана такая тема)",
    "once_a_day": "Раз в день",
    "once_a_week": "Раз в неделю",
    "once_a_month": "Раз в месяц",
    "select_period": "Выберите период, в котором Вам будут приходить новости:",
    "select_time_of_day": "Выберите время дня или введите сами (по московскому вермени, без минут):",
    "select_day_of_month":
        "Выберите день месяца или введите сами (если такого дня не будет в месяце, то будет выбираться последний день):",
    "select_day_of_week": "Выберите день недели:",
    "subscribe_success": "Вы успешно подписаны на новости этого университета!",
    "subscribe_failure": "У Вас уже выбран этот университет)",
    "unsubscribe_from_everything": "Отписаться от всего",
    "unsubscribe_success": "Вы успешно отписались от этого университета",
    "unsubscribe_failure": "Вы еще не подписаны на этот университет",
    "unsubscribe_from_everything_success": "Вы успешно отписались от всех университетов",
    "no_news": "Новостей за данный период нет(",
    "news": "Новости:",
    "continuation": "Продолжение:",
    "few_first_news": "Первые {} новостей",
}
